- .github/workflows/python-publish.yml
- README.md
- pennylane_snowflurry/_version.py
- pennylane_snowflurry/execution_config.py
- pennylane_snowflurry/pennylane_converter.py
- pennylane_snowflurry/snowflurry_device.py
- pyproject.toml
- tests/test_pennylaneSubroutine.py
- tests/test_pyjulia-snowflurry.py
- Support for individual readouts 
- Support for combination of PennyLane's measurement process
- Support for preprocessing transform *decompose* which allow decomposing circuits into supported circuits before sending them through the Julia env
- Tidied up some of the code comments and functions docstring
- Updated the dictionnary mapping supported operations
- Somewhat reorganized test structure, will proceed more seriously in upcoming development (does not require review atm)
> Release onto main

- tests/test_pennylaneConverter.py
- tests/test_snowflurryQubitDevice.py
Updated test, but will be overhauled later
close #25
> 25-update-tests-so-tests-can-succeeds

- pyproject.toml
Ensures we include packages (and sub-modules) when working with Git.
> Use setuptools-scm in pyproject.toml

- pyproject.toml
- requirements-test.txt
Remove `requirements-test.txt` and move its content to the pyproject file.
> Move test requirements to pyproject section

- pyproject.toml
Ensure a clear configuration and remove guessing for setuptools
> Specify sub-modules as well.

- monarq_device.md
Mostly reformatting and and changed two sentences
> reformatting with MarkdownLint

- pyproject.toml
- change description
- change python requirement
- change license statement
- change classifiers for python version, license and dev status
- change pennylane-snowflurry for pennylane-calculquebec everywhere
> changes to pyproject

- pennylane_calculquebec/utility/debug.py
- pennylane_calculquebec/utility/graph.py
- pennylane_calculquebec/utility/kmp.py
- pennylane_calculquebec/utility/plotting.py
- tests/sample_circuits.py
- remove add noise function as it was unused
- make find_closest_wires smaller
- note kmp as currently not used
- note plotting utility as currently not used
- move test circuits in tests
> remove dead code and move sample/test code

- pennylane_calculquebec/utility/monarq_fake.py
monarq fake had a regression error with the transform program. It is now fixed.
> fix error in monarq fake

- pennylane_calculquebec/processing/steps/readout_noise_simulation.py
- tests/test_readout_noise_simulation.py
also removed dead code from the processing step
> test readout noise simulation

- pennylane_calculquebec/processing/config/processing_config.py
- tests/test_processing_config.py
magic methods from the processing configs were not covered. Added coverage for them
> add coverage to processing configs

- pennylane_calculquebec/utility/debug.py
two utility functions added : 
- compute_expval which calculates an expectation value from a probability list (checks if probs are a count dictionary first, and converts it)
- counts_to_probs which converts a counts dictionary to a probability array
> add expection value function and counts to probs

- pennylane_calculquebec/monarq_device.py
- tests/test_api_utility.py
- tests/test_monarq_device.py
two tests have been added : one for the device and one for the api utility script
> handle qml.expval and add tests

- pennylane_calculquebec/utility/debug.py
- tests/test_base_decomp.py
- tests/test_debug_utility.py
- tests/test_optimization.py
each function is covered 100%
some functions were dead code, they were removed
> added unit tests for debug utility

- pennylane_calculquebec/processing/processing_exception.py
- pennylane_calculquebec/processing/steps/decompose_readout.py
- tests/test_decompose_readout.py
- use pennylane methods to accept any hermitian as an observable
- update tests accordingly
> accept any observable supported by pennylane

- doc/for_developers/using_custom_gates.ipynb
- doc/for_developers/using_custom_steps.ipynb
- doc/for_developers/using_different_backends.ipynb
- pennylane_calculquebec/processing/config/processing_config.py
- pennylane_calculquebec/processing/steps/readout_error_mitigation.py
Mitigation steps didn't apply the new backend logic + there was no doc to explain how different backends worked
> apply backend logic to mitigation + new doc

- pennylane_calculquebec/processing/monarq_preproc.py
- pennylane_calculquebec/processing/optimization_methods/iterative_commute_and_merge.py
- pennylane_calculquebec/processing/steps/decompose_readout.py
- tests/test_decompose_readout.py
- tests/test_readout_mitigation.py
- add method in preprocessor to unpack box arrays before executing
- update tests
> unpack array boxes upon preprocessing

- pennylane_calculquebec/API/adapter.py
- pennylane_calculquebec/API/retry_decorator.py
create a decorator which retries a function n times or until it doesnt raise an exception
> add retry decorator

- pennylane_calculquebec/API/job.py
- pennylane_calculquebec/monarq_data.py
- pennylane_calculquebec/monarq_device.py
- pennylane_calculquebec/processing/steps/gate_noise_simulation.py
- pennylane_calculquebec/processing/steps/readout_noise_simulation.py
- tests/test_gate_noise_simulation.py
- tests/test_integration.py
- tests/test_job.py
- tests/test_monarq_data.py
- tests/test_monarq_device.py
make the cache a dictionary which separates caches for the two machines
> discern caching for different backends + job events bugfix

- .idea/.gitignore
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/pennylane-calculquebec.iml
- .idea/vcs.xml
- pennylane_calculquebec/julia_setup.py
- pennylane_calculquebec/logger.py
- pennylane_calculquebec/monarq_backup.py
- pennylane_calculquebec/monarq_data.py
- pennylane_calculquebec/monarq_device.py
- pennylane_calculquebec/monarq_sim.py
- pennylane_calculquebec/pennylane_converter.py
- pennylane_calculquebec/processing/custom_gates.py
- pennylane_calculquebec/processing/monarq_postproc.py
- pennylane_calculquebec/processing/monarq_preproc.py
- pennylane_calculquebec/processing/optimization_methods/iterative_commute_and_merge.py
- pennylane_calculquebec/processing/steps/base_decomposition.py
- pennylane_calculquebec/processing/steps/gate_noise_simulation.py
- pennylane_calculquebec/processing/steps/native_decomposition.py
- pennylane_calculquebec/processing/steps/optimization.py
- pennylane_calculquebec/processing/steps/placement.py
- pennylane_calculquebec/processing/steps/readout_error_mitigation.py
- pennylane_calculquebec/processing/steps/readout_noise_simulation.py
- pennylane_calculquebec/processing/steps/routing.py
- pennylane_calculquebec/snowflurry_device.py
- tests/test_logger.py
J'ai ajouté une fonctionnalité de logger à travers tout le code où survient l'erreur.
Elle ajoute la fonctionnalité de pouvoir trouver d'où viennent les erreurs dans le code directement à l'aide d'un logger
Seulement générer une erreur comme dans l'image plus bas et il va avoir un fichier.log de créé avec le log dedans
resolve #147 
Code pour générer l'erreur
Fichier .log creer
Contenu du fichier .log
> Issue147 resolved

- pennylane_calculquebec/monarq_data.py
- pennylane_calculquebec/monarq_device.py
- pennylane_calculquebec/monarq_sim.py
- pennylane_calculquebec/processing/custom_gates.py
- pennylane_calculquebec/processing/monarq_postproc.py
- pennylane_calculquebec/processing/monarq_preproc.py
- pennylane_calculquebec/processing/optimization_methods/iterative_commute_and_merge.py
- pennylane_calculquebec/processing/steps/base_decomposition.py
- pennylane_calculquebec/processing/steps/gate_noise_simulation.py
- pennylane_calculquebec/processing/steps/native_decomposition.py
- pennylane_calculquebec/processing/steps/optimization.py
- pennylane_calculquebec/processing/steps/placement.py
- pennylane_calculquebec/processing/steps/readout_error_mitigation.py
- pennylane_calculquebec/processing/steps/readout_noise_simulation.py
- pennylane_calculquebec/processing/steps/routing.py
- pennylane_calculquebec/pydoc_generator.py
- pennylane_calculquebec/utility/graph.py
J'ai enlevé les try catch qui faisaient que les tests ne passaient pas.
J'ai résolu le problème des tests qui ne passaient pas
resolve #
> Test not passing

- pennylane_calculquebec/monarq_data.py
- pennylane_calculquebec/monarq_device.py
- pennylane_calculquebec/monarq_sim.py
- pennylane_calculquebec/processing/custom_gates.py
- pennylane_calculquebec/processing/monarq_postproc.py
- pennylane_calculquebec/processing/monarq_preproc.py
- pennylane_calculquebec/processing/optimization_methods/iterative_commute_and_merge.py
- pennylane_calculquebec/processing/steps/base_decomposition.py
- pennylane_calculquebec/processing/steps/gate_noise_simulation.py
- pennylane_calculquebec/processing/steps/native_decomposition.py
- pennylane_calculquebec/processing/steps/optimization.py
- pennylane_calculquebec/processing/steps/placement.py
- pennylane_calculquebec/processing/steps/readout_error_mitigation.py
- pennylane_calculquebec/processing/steps/readout_noise_simulation.py
- pennylane_calculquebec/processing/steps/routing.py
- pennylane_calculquebec/pydoc_generator.py
- pennylane_calculquebec/utility/graph.py
Reverts calculquebec/pennylane-calculquebec#181
> Revert "Test not passing"

- pennylane_calculquebec/monarq_device.py
- pennylane_calculquebec/monarq_sim.py
- pennylane_calculquebec/processing/steps/gate_noise_simulation.py
- pennylane_calculquebec/processing/steps/native_decomposition.py
- pennylane_calculquebec/processing/steps/optimization.py
- pennylane_calculquebec/processing/steps/placement.py
- pennylane_calculquebec/processing/steps/routing.py
J'ai enlevé les try catch qui faisaient que les tests ne passaient pas.
J'ai résolu le problème des tests qui ne passaient pas
resolve #
> Test not passing only essential
